[package]
name = "frxe-desktop"
version = "0.1.0"
edition = "2021"
description = "Frxe Desktop"
authors = ["void"]

[lib]
name = "frxe_desktop_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "protocol-asset"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
tokio = { version = "1", features = ["fs", "io-util", "macros", "process", "rt-multi-thread", "sync"] }
regex = "1"
sysinfo = "0.37"
urlencoding = "2"
walkdir = "2"

[dev-dependencies]
tempfile = "3"
